class StringText {
  static const String yourcardinfo = 'Your card information';
  static const String allcreditcard = 'All Credit Card';
  static const String add = 'Sdd';
  static const String visa = 'Visa';
  static const String yourcardowner = 'Your Card Owner';
  static const String latest = 'Latest';
  static const String transactions = 'Transactions';
  static const String creditcard = 'Credit Card';
  static const String totalbalance = 'Total Balance';
  static const String lastreceipent = 'Last Receipent';
  static const String sendto = 'Send To';
  static const String optimizeperformance = 'Optimize Performance';
  static const String history = 'History';
  static const String income = 'Income';
  static const String outcome = 'Outcome';
  static const String daily = 'Daily';
  static const String weekly = 'Weekly';
  static const String januari2003 = 'January 2003';
  static const String februari2003 = 'February 2003';
  static const String maret2003 = 'Maret 2003';
  static const String now = 'Now';
  static const String usd = 'USD';
  static const String analitik = 'Analitik';
  static const String notransactions = '  No transactions yet, add one!';
  static const String nohistoryaddDatafromHome = 'add data from home';}
